### ISSUE TITLE
Discussion: use for regular liveview?

### ISSUE THREAD

**Issue by dustinfarris** [livebook-dev/kino_maplibre#40]
Please lmk if this should be moved to a different forum.

Wondering if there's any thought around making kino+maplibre a thing for regular liveview outside of livebook?  Specifically the event-handling here looks like it could be useful in other contexts.

**Comment by dustinfarris** [comment]
I see this has been rejected more broadly in https://github.com/livebook-dev/kino/issues/100.

> There are no plans for this. Making it work within another web application would require reimplementing tons of Livebook features we don't plan to work on at the moment.

**Comment by jonatanklosko** [comment]
You could use [maplibre](https://github.com/livebook-dev/maplibre) to build the map specification, but you'd need to implement the JS part that renders the map from specification ([like this](https://github.com/livebook-dev/kino_maplibre/blob/main/lib/assets/maplibre/main.js)). For vega-lite it's a bit more straightforward because the whole specification is JSON, in maplibre on the other hand certain elements (like markers) need to be added with the JS API.
